project:
  type: website
  output-dir: docs

website:
  site-url: https://21centuryweather.github.io/
  open-graph: true
  title: "The 21st Century Weather Toolkit"
  description: "The 21st Century Weather Centre's software and documentation."
  favicon: logo.png
  navbar:
    logo: logo.png
    title: "The 21st Century Weather Toolkit"

format:
  html:
    theme: [cosmo, custom.scss]

editor: visual

