project:
  type: website
  output-dir: docs

website:
  site-url: https://21centuryweather.github.io/
<<<<<<< HEAD
  open-graph:
=======
  open-graph: true
>>>>>>> 41a1bcd9cb66bfc5a4202dd0f4babf75a80b80e2
    site-name: "The 21st Century Weather Toolkit"
    description: "The 21st Century Weather Centre's software and documentation."
    image: logo.png  
  favicon: logo.png
  navbar:
    logo: logo.png
    title: "The 21st Century Weather Toolkit"

format:
  html:
    theme: [cosmo, custom.scss]

editor: visual

